import {
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowRightFromLine,
  ArrowRightToLine,
  ArrowUp,
  Blocks,
  CaseSensitive,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardPaste,
  Copy,
  CopyX,
  Database,
  Delete,
  Download,
  Eraser,
  Files,
  Folder,
  FolderOpen,
  Funnel,
  Hash,
  House,
  Layers,
  Layers2,
  ListX,
  type LucideIcon,
  type LucideProps,
  Maximize,
  Menu,
  MessageSquare,
  Minimize,
  Minus,
  Moon,
  Newspaper,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelRight,
  PanelTop,
  Pencil,
  Play,
  Plus,
  Puzzle,
  RefreshCw,
  Regex,
  Replace,
  ReplaceAll,
  RotateCcw,
  RotateCcwClock,
  Save,
  Search,
  Settings,
  SlidersHorizontal,
  Square,
  Sun,
  TextWrap,
  Trash,
  Type,
  Upload,
  WholeWord,
  Workflow,
  Wrench,
  X,
  Zap
} from "lucide-react"
import { createElement, forwardRef } from "react"

/**
 * Filled variant of an outline Lucide icon, for toggles whose "on" state
 * reads as solid (e.g. Group Tabs By Tool)
 */
const filled = (Icon: LucideIcon): LucideIcon => forwardRef<SVGSVGElement, LucideProps>(
  (props, ref) => createElement(Icon, { ...props, ref, fill: "currentColor" })
)

/**
 * Every icon in the app, from Lucide (https://lucide.dev). Keys are the app's
 * own names so call sites read by purpose, not by Lucide's naming.
 */
export const Icons = {
  Back: ArrowLeft,
  ChevronLeft,
  ChevronRight,
  WordWrap: TextWrap,
  NormalScreen: Minimize,
  Tool: Wrench,
  Filter: Funnel,
  FilterSolid: filled(Funnel),
  Feedback: MessageSquare,
  ThemeDark: Moon,
  ThemeLight: Sun,
  Folder,
  Extensions: Blocks,
  PanelBottom,
  Check,
  ChevronDown,
  ChevronUp,
  Search,
  Documents: Files,
  Trash,
  Untrash: ArchiveRestore,
  BackspaceFill: Delete,
  Box: Square,
  Clean: Eraser,
  Database,
  Palette,
  PanelTop,
  Type,
  Upload,
  Close: X,
  Download,
  Gear: Settings,
  Hash,
  FullScreen: Maximize,
  Extension: Puzzle,
  History: RotateCcwClock,
  Home: House,
  Layers,
  Layers2,
  Minimize: Minus,
  Newspaper,
  PanelLeft,
  Plus,
  Refresh: RefreshCw,
  PanelRight,
  Reset: RotateCcw,
  Minus,
  Restore: ArchiveRestore,
  Run: Play,
  RunFilled: filled(Play),
  Settings: SlidersHorizontal,
  ThreeLineHorizontal: Menu,
  ThreeLineVertical: Workflow,
  Thunder: Zap,

  // Context menu actions
  Copy,
  Paste: ClipboardPaste,
  PickFile: FolderOpen,
  SaveToFile: Save,
  CloseOthers: ListX,
  CloseAll: CopyX,
  Rename: Pencil,
  AddInput: ArrowRightToLine,
  AddOutput: ArrowRightFromLine,

  // Editor find & replace
  ArrowUp,
  ArrowDown,
  MatchCase: CaseSensitive,
  MatchWholeWord: WholeWord,
  Regex,
  Replace,
  ReplaceAll
} satisfies Record<string, LucideIcon>

export type { LucideIcon as Icon }
