import { createTheme } from "@vanilla-extract/css"

import { themeableTokens } from "../styleTokens.css"

export const darkThemeClass = createTheme(themeableTokens, {
  borderColor: "#2a2a2a",
  textColor: "#e0e0e0",
  iconColorFilter: "invert(90%) sepia(6%) saturate(178%) hue-rotate(187deg) brightness(94%) contrast(88%)",
  colorOppositeColor: "#ffffff",
  appTitlebarBackgroundColor: "#1a1b1d",
  buttonBackgroundColor: "#181818",
  buttonBackgroundColorHover: "#26282a",
  buttonBackgroundColorActive: "#1a1c1e",
  buttonBorderColor: "#3e3e3e",
  buttonBorderColorHover: "#3e3e3e",
  buttonBorderColorActive: "#3e3e3e",
  backgroundMain: "#1a1b1d",
  backgroundContent: "#222429",
  activitybarBackgroundColor: "#181818",
  activitybarItemBackgroundColorHover: "#5a5b5e",
  activitybarItemBackgroundColorActive: "#434549",
  primarySidebarBackgroundColor: "#1a1b1d",
  secondaySidebarBackgroundColor: "#1a1b1d",
  bottomPanelBackgroundColor: "#181818",
  statusbarBackgroundColor: "#181818",
  inputOutputBackgroundColor: "#292a30",
  inputOutputBorderColor: "#353535",
  inputOutputBorderColorHover: "var(--input-output-border-color)",
  inputOutputBorderColorActive: "var(--input-output-border-color)",
  sessionTabbarBackgroundColor: "#1a1b1d",
  sessionTabbarColor: "#1a1b1d",
  sessionTabbarColorHover: "#1f2022",
  sessionTabbarTextColor: "#939393",
  sessionTabbarTextColorActive: "white",
  appletHeaderBackgroundColor: "#181818",
  appletViewerBackgroundColor: "#1e1f22",
  toolSidebarTextColor: "#cfcfcf",
  toolSidebarTextColorActive: "#ffffff",
  toolSidebarIconColor: "invert(99%) sepia(3%) saturate(156%) hue-rotate(232deg) brightness(106%) contrast(62%)",
  toolSidebarIconColorActive: "invert(98%) sepia(1%) saturate(321%) hue-rotate(234deg) brightness(116%) contrast(100%)",
  settingsViewBackgroundColor: "#202124",
  settingsViewCardBackgroundColor: "#202124",
  scrollbarTrackBackgroundColor: "transparent",
  scrollbarThumbBackgroundColor: "#393a3f",
  scrollbarThumbBackgroundColorHover: "#555",
  scrollbarThumbBorderRadius: "4px"
})
