import { createGlobalThemeContract, createTheme } from "@vanilla-extract/css"

import { themeableTokens } from "../styleTokens.css"

export const darkThemeClass = createTheme(createGlobalThemeContract(themeableTokens), {
  borderColor: "#313131",
  textColor: "#e0e0e0",
  iconColorFilter: "invert(90%) sepia(6%) saturate(178%) hue-rotate(187deg) brightness(94%) contrast(88%)",
  colorOppositeColor: "#ffffff",
  buttonBackgroundColor: "#262626",
  buttonBackgroundColorHover: "#26282a",
  buttonBackgroundColorActive: "#1a1c1e",
  buttonBorderColor: "#3e3e3e",
  buttonBorderColorHover: "#3e3e3e",
  buttonBorderColorActive: "#3e3e3e",
  backgroundMain: "#1a1b1d",
  backgroundContent: "#222429",
  activitybarBackgroundColor: "#1a1b1d",
  activitybarItemBackgroundColorHover: "#5a5b5e",
  activitybarItemBackgroundColorActive: "#434549",
  primarySidebarBackgroundColor: "#222429",
  statusbarBackgroundColor: "#181818",
  inputOutputBackgroundColor: "#1e1e1e",
  inputOutputBorderColor: "var(--border-color)",
  inputOutputBorderColorHover: "color-mix(in srgb, var(--border-color), var(--opposite-color) 7%)",
  inputOutputBorderColorActive: "var(--input-output-border-color-hover)",
  sessionTabbarBackgroundColor: "#1a1b1d",
  sessionTabbarColor: "#1a1b1d",
  sessionTabbarColorHover: "#1f2022",
  sessionTabbarTextColor: "#939393",
  sessionTabbarTextColorActive: "white",
  appletHeaderBackgroundColor: "#181818",
  appletViewerBackgroundColor: "#202124",
  toolSidebarTextColor: "#cfcfcf",
  toolSidebarTextColorActive: "#ffffff",
  toolSidebarIconColor: "invert(99%) sepia(3%) saturate(156%) hue-rotate(232deg) brightness(106%) contrast(62%)",
  toolSidebarIconColorActive: "invert(98%) sepia(1%) saturate(321%) hue-rotate(234deg) brightness(116%) contrast(100%)",
  settingsViewBackgroundColor: "#202124",
  settingsViewCardBackgroundColor: "#1f2023",
  scrollbarTrackBackgroundColor: "transparent",
  scrollbarThumbBackgroundColor: "393a3f",
  scrollbarThumbBackgroundColorHover: "#555",
  scrollbarThumbBorderRadius: "4px"
})
