import { createGlobalThemeContract, createTheme } from "@vanilla-extract/css"

import { themeableTokens } from "../styleTokens.css"

export const lightThemeClass = createTheme(createGlobalThemeContract(themeableTokens), {
  borderColor: "#cbcccd",
  textColor: "#0f0f0f",
  iconColorFilter: "invert(23%) sepia(1%) saturate(4546%) hue-rotate(38deg) brightness(105%) contrast(85%)",
  colorOppositeColor: "#939393",
  buttonBackgroundColor: "linear-gradient(0deg, #f7f7f7 0%, #ffffff 100%)",
  buttonBackgroundColorHover: "#efefef",
  buttonBackgroundColorActive: "#ececec",
  buttonBorderColor: "#cbcccd",
  buttonBorderColorHover: "#cbcccd",
  buttonBorderColorActive: "#cbcccd",
  backgroundMain: "#ffffff",
  backgroundContent: "#ffffff",
  activitybarBackgroundColor: "#ffffff",
  activitybarItemBackgroundColorHover: "#dfdddd",
  activitybarItemBackgroundColorActive: "#d6d6d6",
  primarySidebarBackgroundColor: "#f6f8fa",
  statusbarBackgroundColor: "#f6f6f6",
  inputOutputBackgroundColor: "#ffffff",
  inputOutputBorderColor: "var(--border-color)",
  inputOutputBorderColorHover: "color-mix(in srgb, var(--border-color), var(--opposite-color) 50%)",
  inputOutputBorderColorActive: "var(--input-output-border-color-hover)",
  sessionTabbarBackgroundColor: "#ffffff",
  sessionTabbarColor: "#ffffff",
  sessionTabbarColorHover: "#f6f8fa",
  sessionTabbarTextColor: "#585858",
  sessionTabbarTextColorActive: "#000000",
  appletHeaderBackgroundColor: "#ffffff",
  appletViewerBackgroundColor: "#f9f9fc",
  toolSidebarTextColor: "#212418",
  toolSidebarTextColorActive: "#ffffff",
  toolSidebarIconColor: "invert(11%) sepia(7%) saturate(1891%) hue-rotate(34deg) brightness(98%) contrast(92%)",
  toolSidebarIconColorActive: "invert(98%) sepia(1%) saturate(321%) hue-rotate(234deg) brightness(116%) contrast(100%)",
  settingsViewBackgroundColor: "#f9f9fc",
  settingsViewCardBackgroundColor: "#ffffff",
  scrollbarTrackBackgroundColor: "ffffff",
  scrollbarThumbBackgroundColor: "8b8b8b",
  scrollbarThumbBackgroundColorHover: "#555",
  scrollbarThumbBorderRadius: "4px"
})
